package ca.sheridancollege.beans;

import java.util.ArrayList;
import java.util.List;

public class Categories {
	
	private List<List<String>> categoryList = new ArrayList<>();

	public Categories() {
		List<String> foundation = new ArrayList<>();
		foundation.add("1.1 Efflorescence is present on concrete or masonry foundation surface");
		foundation.add("1.2 Interior concrete surefaces are powdery");
		foundation.add("1.3 Concrete surface is flaking");
		foundation.add("1.4 Concrete basement floor is cracked");
		foundation.add("1.5 Concrete floor slab-on-ground has settled in a finished area");
		foundation.add("1.6 No reinforcement in basement concrete slab");
		foundation.add("1.7 Concrete block foundation wall is cracked");
		foundation.add("1.8 Parging (not brush coating) is falling off above grade");
		foundation.add("1.9 Exposed cast-in-place concrete foundation wall has holes in the surface");
		foundation.add("1.10 Cast-in-place concrete foundation wall is cracked ");
		foundation.add("1.11 Condensation in crawl space");
		foundation.add("1.12 Basement wall or floor is damp");
		foundation.add("1.13 Foundation wall leaks");
		foundation.add("1.14 Water leakage through basement floor slab");
		foundation.add("1.15 Brush coating on above grade poured concrete foundation wall is falling off");
		foundation.add("1.16 Basement floor drain is too high");
		foundation.add("1.17 Condensation in cold room/cantina");
		foundation.add("1.18 Water/snow accumulation in basement window wells");
		categoryList.add(foundation);
		
		List<String> floorFraming = new ArrayList<>();
		floorFraming.add("2.1 Wood joist, bean or post is split, checked or cupped");
		floorFraming.add("2.2 Floor framing damaged by weather during construction");
		floorFraming.add("2.3 Loose subfloor");
		floorFraming.add("2.4 Floor Squeaks");
		floorFraming.add("2.5 Finished floor above grade is out of level");
		floorFraming.add("2.6 Springiness, bounce, visible sag when loaded, or shaking is observed in the floor");
		categoryList.add(floorFraming);
		
		List<String> wallFraming = new ArrayList<>();
		wallFraming.add("3.1 Wall is out of plumb");
		wallFraming.add("3.2 Wall is Bowed");
		wallFraming.add("3.3 Malfunction of windows");
		wallFraming.add("3.4 Window glass and or screen is damaged");
		wallFraming.add("3.5 Glass is scratched");
		wallFraming.add("3.6 Glass is cracked");
		wallFraming.add("3.7 Window unit leaks during rain");
		wallFraming.add("3.8 Condensation forming between insulating (factory sealed) glass unit");
		wallFraming.add("3.9 Exterior door is warped");
		wallFraming.add("3.10 Exterior metal door is dented");
		wallFraming.add("3.11 Shrinkage of inserted panels shows raw wood edges on exterior wood doors");
		wallFraming.add("3.12 Cracks and splits in exterior wood doors");
		wallFraming.add("3.13 Exterior door sticks");
		wallFraming.add("3.14 Exterior door will not close completely");
		wallFraming.add("3.15 Plastic moulding on exterior door is deformed");
		wallFraming.add("3.16 Exterior door swings open or closed by itself");
		wallFraming.add("3.17 Exterior door is crooked in the frame");
		wallFraming.add("3.18 Exterior door hardware or decorative metal trim has discoloured");
		wallFraming.add("3.19 Sliding door screen will not stay on track or sliding door does not roll smoothly");
		categoryList.add(wallFraming);
		
		List<String> exteriorFinishing = new ArrayList<>();
		exteriorFinishing.add("4.1 Wood or hardwood or panel-type siding is bowed or wavy");
		exteriorFinishing.add("4.2 Wood or hardwood or panel- type siding- joints not tight");
		exteriorFinishing.add("4.3 Wood or hardwood or panel- type siding fasteners are excessively countersunk into finished surface");
		exteriorFinishing.add("4.4 Lap siding is not install on a straight line");
		exteriorFinishing.add("4.5 Tongue-and-groove wood siding has buckled");
		exteriorFinishing.add("4.6 Wood siding - fastener has stained siding 	");
		exteriorFinishing.add("4.7 Cedar shakes or shingles have “bled” through paint or stain applied by builder");
		exteriorFinishing.add("4.8 Plywood or veneer siding has delaminated");
		exteriorFinishing.add("4.9 Aluminum/vinyl siding is bowed or wavy");
		exteriorFinishing.add("4.10 Aluminum or vinyl siding - colour is faded");
		exteriorFinishing.add("4.11 Aluminum or vinyl siding, trim or accessory is loose");
		exteriorFinishing.add("4.12 Aluminum or vinyl siding trim and accessories - fasteners don’t match siding colour");
		exteriorFinishing.add("4.13 Above-grade masonry veneer cladding (including mortar) is cracked");
		exteriorFinishing.add("4.14 Cut bricks are of different thickness in relation to one another");
		exteriorFinishing.add("4.15 Horizontal masonry joint alignment is not uniform ");
		exteriorFinishing.add("4.16 Mortar splatters and stains on exterior masonry ");
		exteriorFinishing.add("4.17 Efflorescence (typically a white powdery film) is present on masonry exterior finishes");
		exteriorFinishing.add("4.18 Deteriorating masonry ");
		exteriorFinishing.add("4.19 Water leakage at doors and windows or at the top of the foundation ");
		exteriorFinishing.add("4.20 Clay bricks are chipped ");
		exteriorFinishing.add("4.21 Bricks are different colours ");
		exteriorFinishing.add("4.22 Cracks in exterior stucco wall surfaces");
		exteriorFinishing.add("4.23 Exterior stucco is peeling or bubbling ");
		exteriorFinishing.add("4.24 Unsealed gaps between dissimilar cladding materials and penetrations through cladding ");
		exteriorFinishing.add("4.25 Exterior wood trim is split ");
		exteriorFinishing.add("4.26 Exterior wood trim is bowed, twisted or cupped 	");
		exteriorFinishing.add("4.27 Paint on repaired areas doesn’t match ");
		exteriorFinishing.add("4.28 Exterior paint, stain or clear finish blisters and peels ");
		exteriorFinishing.add("4.29 Exterior paint or stain has faded ");
		exteriorFinishing.add("4.30 Mould or mildew is visible on exterior painted surfaces ");
		exteriorFinishing.add("4.31 Leak in exterior wall ");
		exteriorFinishing.add("4.32 Thickness of vertical mortar joints are not uniform in brick or masonry units ");
		categoryList.add(exteriorFinishing);
		
		List<String> roof = new ArrayList<>();
		roof.add("5.1 Roof trusses, riddes or rafters are bowed");
		roof.add("5.2 Roof appears wavy");
		roof.add("5.3 Leaks due to snow or rain driven into the attic through louvers or vents");
		roof.add("5.4 Roof or Flashing leaks");
		roof.add("5.5 Inadequate attic ventilation");
		roof.add("5.6 Ice buildup on the roof");
		roof.add("5.7 Roof shingles have blown off");
		roof.add("5.8 Tabs on asphalt shingles are not lined up");
		roof.add("5.9 Asphalt shingles not sealed");
		roof.add("5.10 Asphalt shingle edges are curled or cupped");
		roof.add("5.11 Asphalt shingles either do not overhang the edge of the roof or hang over too far");
		roof.add("5.12 Shading pattern is visible on an asphalt shingle roof");
		roof.add("5.13 Variation in colour after repairs");
		roof.add("5.14 Uneven roof sheathing causing visible irregularities in the roof surface");
		roof.add("5.15 Roofing nails are exposed");
		roof.add("5.16 Temporary safety straps left on roof");
		roof.add("5.17 Water is trapped under roofing membrane");
		roof.add("5.18 Asphalt roll roofing is blistered but does not admit water");
		roof.add("5.19 Standing water on a flat roof");
		roof.add("5.20 Eavestroughs or downspouts leak");
		roof.add("5.21 Eavestroughs overflow during normal rain");
		roof.add("5.22 Eavestroughs or downspouts not performing properly");
		roof.add("5.23 Eavestroughs don’t drain completely");
		roof.add("5.24 Skylight leaks");
		categoryList.add(roof);
		
		List<String> plumbing = new ArrayList<>();
		plumbing.add("6.1 Inadequate water supply");
		plumbing.add("6.2 The domestic water supply system does not deliver water");
		plumbing.add("6.3 Pipes are leaking");
		plumbing.add("6.4 Faucet or fixture is leaking");
		plumbing.add("6.5 Plumbing pipes are frozen and/or burst");
		plumbing.add("6.6 Bathtub or shower leaks");
		plumbing.add("6.7 Condensation appears on water supply pipes and toilets");
		plumbing.add("6.8 Noisy water pipes or “water hammer”");
		plumbing.add("6.9 Defective plumbing fixtures, appliances or trim fittings");
		plumbing.add("6.10 Cracking or chipping of porcelain, enamel or fibreglass surfaces");
		plumbing.add("6.11 Lightweight (fibreglass and acrylic) bathtub or shower base flexes and creaks");
		plumbing.add("6.12 Manufactured solid-surface countertop (integrated basin) cracks at the drain");
		plumbing.add("6.13 Toilet takes more than one flush to em");
		plumbing.add("6.14 Sewer, drains or fixtures blocked");
		plumbing.add("6.15 Colour variation in sinks, tubs, toilets or bidets (plumbing fixtures)");
		categoryList.add(plumbing);
		
		List<String> electrical = new ArrayList<>();
		electrical.add("7.1 Fuses blow or circuit breakers trip");
		electrical.add("7.2 Ground-fault circuit interrupter (gfci) trips frequently");
		electrical.add("7.3 Electrical outlets or switches don’t work");
		electrical.add("7.4 Electrical fixture doesn’t work");
		electrical.add("7.5 Receptacle/switch cover plate is not flush with the wall");
		electrical.add("7.6 Exhaust fan duct terminates in attic or crawl space");
		electrical.add("7.7 Interior light fixture tarnished");
		electrical.add("7.8 Ceiling fan vibrates and is noisy");
		categoryList.add(electrical);
		
		List<String> interiorClimateControl  = new ArrayList<>();
		interiorClimateControl.add("8.1 Draft felt at electrical outlet");
		interiorClimateControl.add("8.2 Exterior air infiltration through windows and doors");
		interiorClimateControl.add("8.3 Kitchen or bath fans allow cold air infiltration or drafts");
		interiorClimateControl.add("8.4 Condensation in attic space");
		interiorClimateControl.add("8.5 Condensation and/or frost on windows");
		interiorClimateControl.add("8.6 Condensation on interior ductwork and air handling equipment");
		interiorClimateControl.add("8.7 Insufficient insulation");
		interiorClimateControl.add("8.8 Heating, ventilating or air conditioning (hvac) systems not installed properly");
		interiorClimateControl.add("8.9 Inadequate heating");
		interiorClimateControl.add("8.10 Inadequate cooling");
		interiorClimateControl.add("8.11 Noisy ductwork");
		interiorClimateControl.add("8.12 Ductwork makes noise when floor is walked on- commonly known as “oil canning”");
		interiorClimateControl.add("8.13 Noise can be heard at register");
		interiorClimateControl.add("8.14 Ductwork comes a");
		interiorClimateControl.add("8.15 Condensate line is blocked");
		interiorClimateControl.add("8.16 Air conditioning coolant line leaks");
		interiorClimateControl.add("8.17 There are gaps between heat diffusers, cold air return grilles and ventilation grilles and the adjacent surface");
		categoryList.add(interiorClimateControl);
		
		List<String> wallAndCeilingFinish = new ArrayList<>();
		wallAndCeilingFinish.add("9.1 Ceiling is uneven");
		wallAndCeilingFinish.add("9.2 Ceiling texture is unevenly applied");
		wallAndCeilingFinish.add("9.3 Gypsum wallboard corners are uneven");
		wallAndCeilingFinish.add("9.4 Cracks in interior wall and ceiling surfaces");
		wallAndCeilingFinish.add("9.5 Ceiling/wall joint separation commonly referred to as “truss uplift”");
		wallAndCeilingFinish.add("9.6 Drywall surface blemishes including nail/screw pops, blisters in taped joints, trowel marks, excess joint compound and dents or gouges");
		wallAndCeilingFinish.add("9.7 Finish of painted gypsum wallboard (drywall) varies");
		wallAndCeilingFinish.add("9.8 Finished surface is rough");
		wallAndCeilingFinish.add("9.9 Paint finish is unacceptable");
		wallAndCeilingFinish.add("9.10 Clear interior finishes have deteriorated");
		wallAndCeilingFinish.add("9.11 Paint is splattered on surfaces not intended to be painted");
		wallAndCeilingFinish.add("9.12 Wallcovering is peeling");
		wallAndCeilingFinish.add("9.13 Patterns in wallcovering are mismatched at the edges");
		wallAndCeilingFinish.add("9.14 water penetration behind ceramic tile and bathtub or shower enclosures");
		wallAndCeilingFinish.add("9.15 Mildew or fungus is visible on interior surfaces");
		categoryList.add(wallAndCeilingFinish);
		
		List<String> interiorFinish = new ArrayList<>();
		interiorFinish.add("10.1 Interior door is warped");
		interiorFinish.add("10.2 Bi-fold and sliding doors come off tracks");
		interiorFinish.add("10.3 Pocket door rubs");
		interiorFinish.add("10.4 Door rubs on the doorjamb or does not latch");
		interiorFinish.add("10.5 Wood door panel has split");
		interiorFinish.add("10.6 Door drags on the floor");
		interiorFinish.add("10.7 Gap between the door and the doorjamb is not uniform");
		interiorFinish.add("10.8 Interior door swings open or closes by itself");
		interiorFinish.add("10.9 Doors bind from improperly installed hinges");
		interiorFinish.add("10.10 Hinges are painted");
		interiorFinish.add("10.11 Gaps exist between stair parts");
		interiorFinish.add("10.12 Squeaking stair riser or tread");
		interiorFinish.add("10.13 Gaps exist between railing parts");
		interiorFinish.add("10.14 Stair railings lack rigidity");
		interiorFinish.add("10.15 Joint quality of interior trim and moulding work");
		interiorFinish.add("10.16 Nailheads and fasteners are not properly set or filled");
		interiorFinish.add("10.17 Interior trim is split");
		interiorFinish.add("10.18 Hammer marks are visible on trim");
		interiorFinish.add("10.19 Resin bleeding through painted finish");
		interiorFinish.add("10.20 Wall area around cold room door is unfinished");
		interiorFinish.add("10.21 Interior door edge is not painted");
		interiorFinish.add("10.22 Stairs, treads and/or landings are out of level");
		categoryList.add(interiorFinish);
		
		List<String> cabinetsAndCountertops = new ArrayList<>();
		cabinetsAndCountertops.add("11.1 Gap between cabinets and ceilings or walls");
		cabinetsAndCountertops.add("11.2 Cabinets do not line up with each other");
		cabinetsAndCountertops.add("11.3 Cabinet doors and drawer faces are warped");
		cabinetsAndCountertops.add("11.4 Cabinet door or drawer binds or rubs");
		cabinetsAndCountertops.add("11.5 Cabinet doors will not stay closed");
		cabinetsAndCountertops.add("11.6 Laminated countertop (including seams, joints or edges) has swelled");
		cabinetsAndCountertops.add("11.7 Laminated countertop is delaminated");
		cabinetsAndCountertops.add("11.8 Cracks in countertop surfaces");
		cabinetsAndCountertops.add("11.9 Scratches/chips on countertops");
		cabinetsAndCountertops.add("11.10 Seams (joints) in stone countertops are too wide or open");
		cabinetsAndCountertops.add("11.11 Surface pits, fissures or veins in natural stone countertops");
		categoryList.add(cabinetsAndCountertops);
		
		List<String> flooring = new ArrayList<>();
		flooring.add("12.1 Transition between different types of flooring is not flush");
		flooring.add("12.2 Finished floor is uneven");
		flooring.add("12.3 Pattern of finished flooring is out of alignment with adjacent wall surfaces");
		flooring.add("12.4 Carpet seam is visible");
		flooring.add("12.5 Carpet is loose or stretching has occurred");
		flooring.add("12.6 Spots or fading on carpet");
		flooring.add("12.7 Carpet not uniform in colour");
		flooring.add("12.8 Carpet has dark stains around perimeter of rooms and at heating registers");
		flooring.add("12.9 Hollow areas in underpad below carpet surface");
		flooring.add("12.10 Protrusions appear on the surface of resilient flooring without breaking through");
		flooring.add("12.11 Resilient sheet flooring is loos");
		flooring.add("12.12 Resilient flooring joints not tight");
		flooring.add("12.13 Bubbles appear on vinyl flooring surface");
		flooring.add("12.14 Patterns on sheet vinyl flooring are not aligned across seams");
		flooring.add("12.15 Resilient (flexible) floor tile is loose");
		flooring.add("12.16 Patterns or corners of resilient floor tile are misaligned");
		flooring.add("12.17 Yellowing appears on surface of vinyl flooring");
		flooring.add("12.18 Dye lot variations in vinyl flooring");
		flooring.add("12.19 Variation in colour occurring during repair of vinyl flooring");
		flooring.add("12.20 Cracks developing between strips of hardwood or parquet flooring");
		flooring.add("12.21 Strip hardwood flooring is cupped (high edges)");
		flooring.add("12.22 The surface of one strip of hardwood or parquet flooring is higher than another");
		flooring.add("12.23 Floor finish on wood flooring is not uniform");
		flooring.add("12.24 Finish on wood flooring has cracked, blistered, bubbled, or peeled resulting in detachment of finish");
		flooring.add("12.25 Crowning of strip hardwood flooring has occurred (centre of strip is higher than edges)");
		flooring.add("12.26 Wood flooring buckles and detaches from substrate");
		flooring.add("12.27 Knots and colour variation in strip wood flooring");
		flooring.add("12.28 Splinters occur in strip wood flooring");
		flooring.add("12.29 “Sticker burn” appears on surface of strip flooring");
		flooring.add("12.30 Ceramic/porcelain tile, marble or stone flooring is broken or loose (including marble transitions)");
		flooring.add("12.31 Cracks appearing in grouting of ceramic tile joints or at junctions with other materials such as bathtubs");
		flooring.add("12.32 Adjacent marble units or ceramic tile surfaces installed at different elevations");
		flooring.add("12.33 Grout is not a uniform colour");
		flooring.add("12.34 Dye lot variations in ceramic floor tiles");
		flooring.add("12.35 Variation in colour in natural stone tile installations (granite, marble, travertine, slate and limestone)");
		flooring.add("12.36 Gaps developing at ends or along strips of laminate flooring");
		flooring.add("12.37 Laminate flooring is cupped (high edges)");
		flooring.add("12.38 Laminate flooring buckles");
		flooring.add("12.39 Laminate flooring strips are dented, scratched and/or chipped");
		categoryList.add(cabinetsAndCountertops);
		
		List<String> chimneysAndFireplace = new ArrayList<>();
		chimneysAndFireplace.add("13.1 Joint or crack in chimney cap allows water leak");
		chimneysAndFireplace.add("13.2 Roof flashing leaks at chimney");
		chimneysAndFireplace.add("13.3 Bricks breaking up on surface of chimney");
		chimneysAndFireplace.add("13.4 Chimney serving solid-fuel-burning (wood, pellet, etc.) Appliance does not draw properly");
		chimneysAndFireplace.add("13.5 Fireplace firebox paint colour changed");
		chimneysAndFireplace.add("13.6 Firebrick is broken");
		categoryList.add(chimneysAndFireplace);
		
		List<String> garageAndExterior = new ArrayList<>();
		garageAndExterior.add("14.1 Garage floor has heaved or settled");
		garageAndExterior.add("14.2 Concrete garage floor is cracked");
		garageAndExterior.add("14.3 No reinforcement in garage slab");
		garageAndExterior.add("14.4 Garage doors do not operate properly");
		garageAndExterior.add("14.5 Garage doors (vehicular and man-doors) allow entrance of snow or water");
		garageAndExterior.add("14.6 Water accumulates on garage floor");
		garageAndExterior.add("14.7 Asphalt or concrete driveway has cracked");
		garageAndExterior.add("14.8 Driveway has settled");
		garageAndExterior.add("14.9 Sod/seeding not completed");
		garageAndExterior.add("14.10 The shrubs, tree(s), plants, or sod have died");
		garageAndExterior.add("14.11 Tree stumps have been left on the property");
		garageAndExterior.add("14.12 Water ponding in surface grading of the site");
		garageAndExterior.add("14.13 Settling, heaving or separating of landings or steps");
		garageAndExterior.add("14.14 Exterior deck is springy or shaky");
		garageAndExterior.add("14.15 Exterior deck railing is shaky");
		garageAndExterior.add("14.16 Deck board spacing is not uniform");
		garageAndExterior.add("14.17 Exterior wood handrails have slivers");
		garageAndExterior.add("14.18 Exterior deck is out of level");
		garageAndExterior.add("14.19 Floor decking boards are split, warped or cupped");
		garageAndExterior.add("14.20 Stain colour variations on wood deck");
		garageAndExterior.add("14.21 Nailheads stick up on deck surface");
		garageAndExterior.add("14.22 Stains on exterior decking from nailheads");
		garageAndExterior.add("14.23 Twisting of open-end beams");
		categoryList.add(garageAndExterior);
		
	}

	
}
